### ISSUE TITLE
Custom encoding

### ISSUE THREAD

**Issue by ArthaTi** [Mr-Xcoder/Cthulhu#7]
Hello there,

I'm creating my own language that in some concepts is similar to Cthulu. 

I found out that both my lang and this has the same problem - multibyte characters.

Functions/constants here use characters which span 2 or 3 bytes, which just make it lose score. I realized it, when PHP `var_dump("Đ")` shown me `string(2)` instead of `string(1)`. I thought there might be a space or what else, but it was just 1 character saved in 2 bytes.

Sadly, to re-gain the score, you should make the parser read custom bytes (just like Jelly does). Say, in unicode all characters 0-31 are only control ones, which you don't need. Your language **loses lots of score** because of them (ex. char 260 uses 2 bytes, while it could use just 1).

I asked a question on PPCG meta today, now marked as duplicate, but you might find it helpful: https://codegolf.meta.stackexchange.com/questions/13745/

(sorry, if it's already here, I don't write in Python)

Thanks.

**Comment by Mr-Xcoder** [comment]
@Soaku  I will add a custom encoding, of course. If I won't be able to do that, I'll just convert it to ASCII later on. Nearly all our golfing languages have custom encodings (i.e Jelly, 05AB1E, Gaia, SOGL, Charcoal), and so will Cthulhu. As of now, I haven't even finished the built-ins and didn't even write the actual interpreter, so this is not among my concerns right now. These are things I will do later in the development process.  Good luck with your language!
